### ISSUE TITLE
'NoneType' object has no attribute 'queries'

### ISSUE THREAD

**Issue by T-baby** [sparckles/Robyn#566]
### Bug Description

If I use middleware that adds a global before_request, this will get an exception.

`ERROR:robyn.server:Error while executing before middleware function for endpoint `/`: 'NoneType' object has no attribute 'queries'`

### Steps to Reproduce

1. My code：

```python
@app.before_request()
async def before_req(request):
    print("before_request")
    print(request)
    return
```

2. Access any url.

### Your operating system

MacOS

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

**Comment by IdoKendo** [comment]
Hey @T-baby 👋 
The `before_request` decorator requires the function it wraps to return a `Request` - Since you are returning `None` it fails.
For an immediate fix, you can just add `return request` at the end instead of a blank return.

@sansyrox Maybe the docs needs to reflect that, or the behavior needs to handle cases that `before_request` wrapped function doesn't return a `Request`, WDYT?

**Comment by T-baby** [comment]
It works. I feel like the before_request shouldn't force a return or have a friendlier error message.

**Comment by sansyrox** [comment]
@T-baby , I agree with you 😊 Let's keep the issue open!

**Comment by sansyrox** [comment]
And thanks for the triage @IdoKendo 😊

**Comment by sansyrox** [comment]
Hey @T-baby 👋 

This is the expected behavior, however, the response should be implicitly casted. https://github.com/sparckles/Robyn/issues/793

Adding documentation for this behaviour tho.

Do let me know if you have any more suggestions/questions 😄
